### PR TITLE
fix `connect` `dial` before wrap ssl, revert partial of https://github.co…

### PR DESCRIPTION
**Pull request by bung87**
…m/nim-lang/smtp/commit/7eae0f0d834ffe6517031b4570e9aa86ea7c26bf

fix https://github.com/nim-lang/smtp/issues/12

### CODE REVIEW

**Comment by ringabout** [comment]
ref https://github.com/nim-lang/smtp/pull/7

cc @mildred

**Comment by ThomasTJdev** [comment]
What do we need to get this PR merged? @mildred ?

**Comment by ThomasTJdev** [comment]
Any progress here? What would be needed to proceed?

**Comment by ringabout** [comment]
Can we revert https://github.com/nim-lang/smtp/commit/7eae0f0d834ffe6517031b4570e9aa86ea7c26bf fully?

**Comment by bung87** [comment]
I don't think worth to.

**Comment by ringabout** [comment]
> I can remove/redo the code and provide a PR with a detailed description -

It would be appreicated, thank you!

**Comment by bung87** [comment]
close as problem gone by revert

**Pull request closed without merging**
